name: Experiment
on: 
  schedule:
    - cron: '* * * * *'
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
    - name: Run
      run: curl $NOTIFICATON_URL -d 'Test github actions schedule'
      env:
        NOTIFICATON_URL: ${{ secrets.NOTIFICATON_URL }}
