name: Experiment
on: 
  schedule:
    - cron: '* * * * *'
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
    - name: Run
      run: curl $NOTIFICATION_URL -d 'Test github actions schedule'
      env:
        NOTIFICATION_URL: ${{ secrets.NOTIFICATION_URL }}
